services:
  - type: worker
    name: mbti-morrowind-bot
    envVars:
      - key: BOT_TOKEN
        fromService:
          name: global
          key: BOT_TOKEN
      - key: ADMIN_ID
        fromService:
          name: global
          key: ADMIN_ID
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
